version: "3"
services:
  client:
    build: ./
    ports:
      - "80:80"
    container_name: client
  nosql_db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: app-nosql-db
  sql_db:
    image: postgres
    restart: always
    env_file:
      - postgres.env
    volumes:
      - /tmp/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: app-sql-db